import React from 'react';
import { Sparkles, FileText, CheckCircle2, Copy, Download } from 'lucide-react';

export default function ExecutiveSummaryPanel({ graphMeta, docCount, summaryText }) {
  const defaultSummary = [
    "Synthesized cross-document analysis across research literature.",
    "Mapped entity relationships, identifying high-density concept nodes and methodologies.",
    "Cross-verified claim evidence scores with direct paragraph citation links."
  ];

  const summaryBullets = summaryText
    ? summaryText.split(/\d+\.\s+/).filter(Boolean)
    : defaultSummary;

  const handleCopySummary = () => {
    const fullText = summaryBullets.join('\n• ');
    navigator.clipboard.writeText(fullText);
    alert('Executive Summary copied to clipboard!');
  };

  return (
    <div className="bg-slate-900/90 rounded-2xl border border-slate-800 p-5 shadow-2xl space-y-4">
      
      {/* Header */}
      <div className="flex items-center justify-between pb-3 border-b border-slate-800">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white">AI Executive Synthesis</h3>
            <p className="text-[11px] text-slate-400">Generated by Gemini 3 Flash Multi-Model Engine</p>
          </div>
        </div>

        <button
          onClick={handleCopySummary}
          title="Copy Summary"
          className="flex items-center gap-1 text-xs text-slate-400 hover:text-cyan-400 bg-slate-800/80 px-2.5 py-1 rounded-lg border border-slate-700 transition-colors"
        >
          <Copy className="w-3.5 h-3.5" />
          Copy
        </button>
      </div>

      {/* Stats Ribbon */}
      <div className="grid grid-cols-4 gap-2 text-center">
        <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800">
          <p className="text-[10px] text-slate-400 font-mono uppercase">Papers</p>
          <p className="text-sm font-bold text-cyan-400">{docCount || 2}</p>
        </div>
        <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800">
          <p className="text-[10px] text-slate-400 font-mono uppercase">Entities</p>
          <p className="text-sm font-bold text-purple-400">{graphMeta?.totalEntities || 10}</p>
        </div>
        <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800">
          <p className="text-[10px] text-slate-400 font-mono uppercase">Claims</p>
          <p className="text-sm font-bold text-emerald-400">{graphMeta?.totalClaims || 6}</p>
        </div>
        <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800">
          <p className="text-[10px] text-slate-400 font-mono uppercase">Cross-Links</p>
          <p className="text-sm font-bold text-amber-400">{graphMeta?.crossDocumentConnections || 3}</p>
        </div>
      </div>

      {/* Key Bullets */}
      <div className="space-y-2 bg-slate-950/80 p-4 rounded-xl border border-slate-800/80">
        <p className="text-xs font-bold uppercase tracking-wider text-purple-300">Core Findings Overview</p>
        {summaryBullets.map((bullet, idx) => (
          <div key={idx} className="flex items-start gap-2.5 text-xs text-slate-300 leading-relaxed">
            <CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
            <span>{bullet.trim()}</span>
          </div>
        ))}
      </div>

    </div>
  );
}
